import { TeamModel } from '../models/teams';

const teams = [
  new TeamModel({
    _id: '5d7397916de21e04974c6960',
    clubName: 'Arsenal F.C',
    clubCodeName: 'ARS',
    founded: 1886,
    coach: 'Unai Emery',
    logo: 'asernal.png',
    country: 'England',
    stadium: 'Emirates Stadium',
    stadiumCapacity: 60361,
    isDeleted: false,
  }),

  new TeamModel({
    _id: '5d7397916de21e04974c6961',
    clubName: 'Burnley F.C',
    clubCodeName: 'BUR',
    founded: 1882,
    coach: 'Sean Dyche',
    logo: 'burnley.png',
    country: 'England',
    stadium: 'Turf Moor',
    stadiumCapacity: 50361,
    isDeleted: false,
  }),

  new TeamModel({
    _id: '5d7397916de21e04974c6962',
    clubName: 'Chelsea F.C',
    clubCodeName: 'CHE',
    founded: 1905,
    coach: 'Maurizio Sarri',
    logo: 'chelsea.png',
    country: 'England',
    stadium: 'Stamford Bridge',
    stadiumCapacity: 50361,
    isDeleted: false,
  }),

  new TeamModel({
    _id: '5d7397916de21e04974c6963',
    clubName: 'Crystal Palace F.C',
    clubCodeName: 'CRP',
    founded: 1905,
    coach: 'Roy Hodgson',
    logo: 'crystal.png',
    country: 'England',
    stadium: 'Selhurst Park',
    stadiumCapacity: 50361,
    isDeleted: false,
  }),

  new TeamModel({
    _id: '5d7397916de21e04974c6964',
    clubName: 'Everton F.C',
    clubCodeName: 'EVE',
    founded: 1878,
    coach: 'Marco Silva',
    logo: 'everton.png',
    country: 'England',
    stadium: 'Goodison Park',
    stadiumCapacity: 50361,
    isDeleted: false,
  }),

  new TeamModel({
    _id: '5d7397916de21e04974c6965',
    clubName: 'Leicester City',
    clubCodeName: 'LCT',
    founded: 1884,
    coach: 'Brendan Rodgers',
    logo: 'leicester.png',
    country: 'England',
    stadium: 'King Power Stadium',
    stadiumCapacity: 50361,
    isDeleted: false,
  }),

  new TeamModel({
    _id: '5d7397916de21e04974c6966',
    clubName: 'Liverpool F.C',
    clubCodeName: 'LCT',
    founded: 1982,
    coach: 'Jürgen Klopp',
    logo: 'liverpool.png',
    country: 'England',
    stadium: 'Anfield',
    stadiumCapacity: 50361,
    isDeleted: false,
  }),

  new TeamModel({
    _id: '5d7397916de21e04974c6967',
    clubName: 'Manchester United F.C',
    clubCodeName: 'MUN',
    founded: 1878,
    coach: 'Ole Gunnar Solskjær',
    logo: 'manchester.png',
    country: 'England',
    stadium: 'Old Trafford',
    stadiumCapacity: 50361,
    isDeleted: false,
  }),

  new TeamModel({
    _id: '5d7397916de21e04974c6968',
    clubName: 'Manchester City F.C',
    clubCodeName: 'MAC',
    founded: 1880,
    coach: 'Pep Guardiola',
    logo: 'man-city.png',
    country: 'England',
    stadium: 'Etihad Stadium',
    stadiumCapacity: 50361,
    isDeleted: false,
  }),

  new TeamModel({
    _id: '5d7397916de21e04974c6969',
    clubName: 'Newcastle United F.C',
    clubCodeName: 'NWC',
    founded: 1892,
    coach: 'Rafael Benítez',
    logo: 'newcastle.png',
    country: 'England',
    stadium: 'St. James Park',
    stadiumCapacity: 50361,
    isDeleted: false,
  }),

  new TeamModel({
    _id: '5d7397916de21e04974c6970',
    clubName: 'Tottenham Hotspur F.C',
    clubCodeName: 'THP',
    founded: 1882,
    coach: 'Mauricio Pochettino',
    logo: 'tottenham.png',
    country: 'England',
    stadium: 'White Hart Lane',
    stadiumCapacity: 50361,
    isDeleted: false,
  }),

  new TeamModel({
    _id: '5d7397916de21e04974c6971',
    clubName: 'Watford F.C',
    clubCodeName: 'WAT',
    founded: 1881,
    coach: 'Javi Garcia',
    logo: 'watford.png',
    country: 'England',
    stadium: 'Vicarage Road',
    stadiumCapacity: 50361,
    isDeleted: false,
  }),

  new TeamModel({
    _id: '5d7397916de21e04974c6972',
    clubName: 'F.C. Barcelona',
    clubCodeName: 'FCB',
    founded: 1899,
    coach: 'Ernesto Valverde',
    logo: 'barcelona.png',
    country: 'Spain',
    stadium: 'Camp Nou',
    stadiumCapacity: 99354,
    isDeleted: false,
  }),

  new TeamModel({
    _id: '5d7397916de21e04974c6973',
    clubName: 'Real Madrid C.F',
    clubCodeName: 'RMD',
    founded: 1881,
    coach: 'Zinedine Zidane',
    logo: 'real-madrid.png',
    country: 'Spain',
    stadium: 'Santiago Bernabéu',
    stadiumCapacity: 80361,
    isDeleted: false,
  }),
];

export default teams;
